const nameSkins = [
  'YASUO',
  'HIGH NOON YASUO',
  'PROJECT: YASUO',
  'BLOOD MOON YASUO',
  'NIGHTBRINGER YASUO',
  'ODYSSEY YASUO',
  'BATTLE BOSS YASUO',
  'TRUE DAMAGE YASUO',
  'TRUE DAMAGE YASUO PRESTIGE EDITION',
  'SPIRIT BLOSSOM YASUO',
  'TRUTH DRAGON YASUO',
  'DREAM DRAGON YASUO',
];

export { nameSkins };
