const storyLanguages = [
  "An Ionian of deep resolve, Yasuo is an agile swordsman who wields the air itself against his enemies. As a proud young man, he was falsely accused of murdering his master—unable to prove his innocence, he was forced to slay his own brother in self defense. Even after his master's true killer was revealed, Yasuo still could not forgive himself for all he had done, and now wanders his homeland with only the wind to guide his blade.",
  'Um Ioniano de profunda determinação, Yasuo é um espadachim ágil que empunha o próprio ar contra seus inimigos. Como um jovem orgulhoso, ele foi falsamente acusado de assassinar seu mestre - incapaz de provar sua inocência, ele foi forçado a matar seu próprio irmão em legítima defesa. Mesmo depois que o verdadeiro assassino de seu mestre foi revelado, Yasuo ainda não conseguiu se perdoar por tudo o que havia feito, e agora vagueia pátria com apenas o vento para guiar sua lâmina.',
  'Ионийец глубокой решимости, Ясуо — ловкий фехтовальщик, владеющий сам воздух против своих врагов. Как гордый юноша, он был ложно обвинен в убийстве своего хозяина — не в состоянии доказать свою невиновности, он был вынужден убить своего брата в целях самообороны. Даже после того, как истинный убийца его хозяина был раскрыт, Ясуо все еще не мог простить себе всего содеянного и теперь бродит родине, где только ветер направляет ero клинок.',
  'En jonisk med djup beslutsamhet, Yasuo är en smidig svärdsman som använder luften själv mot sina fiender. Som en stolt ung man var han det falskt anklagad för att ha mördat sin herre - oförmögen att bevisa sin oskuld tvingades han döda sin egen bror i självförsvar. Även efter att hans mästares sanna mördare avslöjades, Yasuo fortfarande kunde inte förlåta sig själv för allt han gjort, och nu vandrar hans hemland med bara vinden att styra hans blad.',
  'Yasuo ist ein Ionier von tiefer Entschlossenheit und ein agiler Schwertkämpfer, der schwingt die Luft selbst gegen seine Feinde. Als stolzer junger Mann war er es fälschlich beschuldigt, seinen Meister ermordet zu haben – unfähig, seinen zu beweisen Unschuld war er gezwungen, seinen eigenen Bruder zur Selbstverteidigung zu töten. Selbst nachdem der wahre Mörder seines Meisters enthüllt wurde, ist Yasuo immer noch konnte sich selbst nicht verzeihen, was er getan hatte, und wandert nun umher Heimat mit nur dem Wind, um seine Klinge zu führen.',
  '深い決意を持ったイオニアン、安雄は機敏な剣士であり、彼の敵に対する空気自体。誇り高き青年として、彼は彼の主人を殺害したとして誤って告発された—彼を証明することができない無実、彼は自己防衛で彼自身の兄弟を殺すことを余儀なくされました。師匠の真の殺し屋が明かされた後も、安雄はまだ彼がしたことすべてを許すことができず、今は彼をさまよっている彼の刃を導く風だけの故郷。',
];

export { storyLanguages };
