const hoverMarkupQuote = [
  "Earn in-game rewards and learn more about Riot's games",
  'Face off in the ultimate 5v5 battle arena',
  'Style on your enemies in this 5v5 tactical shooter',
  'A TEAM-BUILDING BATTLE OF WITS',
  'Master every moment in this strategy card game',
  'LEAGUE OF LEGENDS, NOW ON MOBILE',
  'Riot Forge Presents Hextech Mayhem',
  'RISE AGAINST RUIN IN THIS TURN BASED RPG',
  'EXPLORE ZAUN AS EKKO IN THIS ACTION PLATFORMER',
  'A Song Lives Forever',
  'PUBLISHER OF COMPLETABLE EXPERIENCES FROM THE LEAGUE UNIVERSE',
  '',
  '',
  'AN ANIMATED SERIES ON NETFLIX FROM THE WORLD OF LEAGUE OF LEGENDS',
  'THE DEFINITIVE SOURCE FOR THE WORLD OF LEAGUE OF LEGENDS',
  'MUSIC HAS A NEW HOME',
  'UNLEASH PLAY',
  'THE OFFICIAL HOME OF RIOT GAMES MERCH',
  'YOUR MOBILE COMPANION FOR ALL THINGS RIOT GAMES',
  'FROM TECH TO TILT, WE ARE HERE TO HELP YOU',
];

const hoverMarkupSEO = [
  'ARCANE',
  'LEAGUE OF LEGENDS',
  'VALORANT',
  'TEAMFIGHT TACTICS',
  'LEGENDS OF RUNETERRA',
  'LOL: WILD RIFT',
  'HEXTECH MAYHEM',
  'RUINED KING',
  'CONV/RGENCE',
  'SONG OF NUNU',
  'RIOT FORGE GAMES',
  'LOL ESPORTS',
  'VALORANT ESPORTS',
  'ARCANE',
  'UNIVERSE',
  'RIOT GAMES MUSIC',
  'RIOT GAMES',
  'RIOT MERCH',
  'RIOT MOBILE',
  'RIOT SUPPORT',
];

export { hoverMarkupBackground, hoverMarkupQuote, hoverMarkupSEO };
