# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Yasuo The King CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Backend Dependencies
      run: cd BackEnd && npm install
    - name: Run Backend Code
      run: |
        cd BackEnd
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV
        echo "NODE_ENV_TEST=${{ secrets.NODE_ENV_TEST }}" >> $GITHUB_ENV
        echo "DATABASE=${{ secrets.DATABASE }}" >> $GITHUB_ENV
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
        echo "DATABASE_COLLECTION_YASUO=${{ secrets.DATABASE_COLLECTION_YASUO }}" >> $GITHUB_ENV
        echo "DATABASE_COLLECTION_SESSION_SECRET=${{ secrets.DATABASE_COLLECTION_SESSION_SECRET }}" >> $GITHUB_ENV
        echo "DATABASE_COLLECTION_SESSION=${{ secrets.DATABASE_COLLECTION_SESSION }}" >> $GITHUB_ENV
        echo "EMAIL_AUTHOR=${{ secrets.EMAIL_AUTHOR }}" >> $GITHUB_ENV
        echo "MAILTRAP_HOST=${{ secrets.MAILTRAP_HOST }}" >> $GITHUB_ENV
        echo "MAILTRAP_PORT=${{ secrets.MAILTRAP_PORT }}" >> $GITHUB_ENV
        echo "MAILTRAP_USERNAME=${{ secrets.MAILTRAP_USERNAME }}" >> $GITHUB_ENV
        echo "MAILTRAP_PASSWORD=${{ secrets.MAILTRAP_PASSWORD }}" >> $GITHUB_ENV
        echo "BREVO_HOST=${{ secrets.BREVO_HOST }}" >> $GITHUB_ENV
        echo "BREVO_PORT=${{ secrets.BREVO_PORT }}" >> $GITHUB_ENV
        echo "BREVO_KEY_NAME=${{ secrets.BREVO_KEY_NAME }}" >> $GITHUB_ENV
        echo "BREVO_KEY_VALUE=${{ secrets.BREVO_KEY_VALUE }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_REDIRECT=${{ secrets.GOOGLE_CLIENT_REDIRECT }}" >> $GITHUB_ENV
        echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> $GITHUB_ENV
        echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> $GITHUB_ENV
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
        echo "REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}" >> $GITHUB_ENV
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
        echo "JEST_SIGN_SESSION_SECRET=${{ secrets.JEST_SIGN_SESSION_SECRET }}" >> $GITHUB_ENV
        npm run devj
    - name: Wait for Backend to Finish
      run: sleep 10s

    - name: Install Frontend Dependencies
      run: cd FrontEnd && npm install
    - name: Run Frontend Code
      run: |
        cd FrontEnd
        npm run dev
    - name: Wait for Frontend to Finish
      run: sleep 30s

    - name: Run Tests
      run: |
        cd BackEnd
        npm run test
