# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Yasuo The King CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      NODE_ENV_TEST: ${{ secrets.NODE_ENV_TEST }}
      DATABASE: ${{ secrets.DATABASE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_COLLECTION_YASUO: ${{ secrets.DATABASE_COLLECTION_YASUO }}
      DATABASE_COLLECTION_SESSION_SECRET: ${{ secrets.DATABASE_COLLECTION_SESSION_SECRET }}
      DATABASE_COLLECTION_SESSION: ${{ secrets.DATABASE_COLLECTION_SESSION }}
      EMAIL_AUTHOR: ${{ secrets.EMAIL_AUTHOR }}
      MAILTRAP_HOST: ${{ secrets.MAILTRAP_HOST }}
      MAILTRAP_PORT: ${{ secrets.MAILTRAP_PORT }}
      MAILTRAP_USERNAME: ${{ secrets.MAILTRAP_USERNAME }}
      MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
      BREVO_HOST: ${{ secrets.BREVO_HOST }}
      BREVO_PORT: ${{ secrets.BREVO_PORT }}
      BREVO_KEY_NAME: ${{ secrets.BREVO_KEY_NAME }}
      BREVO_KEY_VALUE: ${{ secrets.BREVO_KEY_VALUE }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CLIENT_REDIRECT: ${{ secrets.GOOGLE_CLIENT_REDIRECT }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      JEST_SIGN_SESSION_SECRET: ${{ secrets.JEST_SIGN_SESSION_SECRET }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Backend uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "BackEnd/package-lock.json"
    - name: Frontend uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "FrontEnd/package-lock.json"
        
    - name: Install Backend Dependencies
      run: cd BackEnd && npm install
    - name: Run Backend Code
      run: |
        cd BackEnd
        npm run devj
    - name: Wait for Backend to Finish
      run: sleep 10s

    - name: Install Frontend Dependencies
      run: cd FrontEnd && npm install
    - name: Run Frontend Code
      run: |
        cd FrontEnd
        npm run dev
    - name: Wait for Frontend to Finish
      run: sleep 30s

    - name: Run Tests
      run: |
        cd BackEnd
        npm run test
